---
title: "Pregunta 3"
output: html_document
---

Primero crearemos nuestros boxplots para la variable peso de los atletas de los distintos paises:

```{r}
datosPeso <- datos[complete.cases(datos),]
keep <- c("NOC", "Weight", "Height")

datosPeso <- datosPeso[keep]

# create list of counties in data to loop over 
NOCList <- unique(datosPeso$NOC)

# create for loop to produce ggplot2 graphs 
plotList <- list()
for (i in seq(floor(length(NOCList)/8))) { 
    
    # create plot for each county in df 
    plot <- ggplot(subset(datosPeso, datosPeso$NOC == NOCList[8*i] | 
                            datosPeso$NOC == NOCList[8*i+1] |
                            datosPeso$NOC == NOCList[8*i+2] |
                            datosPeso$NOC == NOCList[8*i+3] |
                            datosPeso$NOC == NOCList[8*i+4] |
                            datosPeso$NOC == NOCList[8*i+5] |
                            datosPeso$NOC == NOCList[8*i+6] |
                            datosPeso$NOC == NOCList[8*i+7]), aes(NOC, Weight, fill=NOC)) + 
      geom_boxplot() +
      labs(title="Grafico Boxplot de Peso de Atletas por Pais",x="Pais (Abreviacion NOC)", y = "Peso Atleta (kg)")
    plotList[[i]] = plot
}

for (i in seq(length(plotList))) {
    print(plotList[[i]])
}

```
Similarmente, tenemos nuestros boxplots para la variable de altura:

```{r}
for (i in seq(floor(length(NOCList)/8))) { 
    
    # create plot for each county in df 
    plot <- ggplot(subset(datosPeso, datosPeso$NOC == NOCList[8*i] | 
                            datosPeso$NOC == NOCList[8*i+1] |
                            datosPeso$NOC == NOCList[8*i+2] |
                            datosPeso$NOC == NOCList[8*i+3] |
                            datosPeso$NOC == NOCList[8*i+4] |
                            datosPeso$NOC == NOCList[8*i+5] |
                            datosPeso$NOC == NOCList[8*i+6] |
                            datosPeso$NOC == NOCList[8*i+7]), aes(NOC, Height, fill=NOC)) + 
      geom_boxplot() +
      labs(title="Grafico Boxplot de Altura de Atletas por Pais",x="Pais (Abreviacion NOC)", y = "Altura Atleta (cm)")
    plotList[[i]] = plot
}

for (i in seq(length(plotList))) {
    print(plotList[[i]])
}
```

